### PR TITLE
reenabled the emergency message

### PR DESCRIPTION
**Pull request by marcincichon**
@sparkdevelopment can you review?

### CODE REVIEW

**Comment by sparkdevelopment** [comment]
@marcincichon Ok to merge - I'd assumed it was a front-end change :)

**Comment by marcincichon** [comment]
@sparkdevelopment let's review this together

**Comment by marcincichon** [comment]
@sparkdevelopment looks good to me

**Comment by sparkdevelopment** [comment]
@marcincichon Looks ok to me too. Happy to merge?

**Pull request merged**
